"""Module 6.2 — Conversation Management schemas.

A *conversation* is the unit of multi-turn interaction.  Each
conversation has an ordered list of :class:`Message` objects.  A
:class:`ConversationContext` is a compact, working-set view of the
conversation that's passed to the orchestrator for context-aware
answer generation.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


# ─── Enums ──────────────────────────────────────────────────────────────────


class Role(str, Enum):
    """Speaker of a conversation message."""

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


class ConversationStatus(str, Enum):
    """Lifecycle state of a conversation."""

    ACTIVE = "active"
    PAUSED = "paused"
    ARCHIVED = "archived"
    EXPIRED = "expired"


# ─── Messages ─────────────────────────────────────────────────────────────


class Message(BaseModel):
    """A single turn in a conversation."""

    model_config = ConfigDict(extra="forbid")

    message_id: str = Field(default_factory=lambda: f"msg-{uuid.uuid4().hex[:12]}")
    role: Role
    content: str = Field(..., min_length=1, description="The message text.")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)
    # Optional references to produced artefacts (e.g. orchestrator
    # request_id, analytics event_id).
    references: Dict[str, str] = Field(default_factory=dict)
    token_estimate: int = Field(0, ge=0, description="Approximate token count.")


# ─── Context window ───────────────────────────────────────────────────────


class ConversationContext(BaseModel):
    """A working-set view of a conversation for prompt injection.

    The context is the slice of the conversation that should be
    surfaced to the orchestrator.  It includes:

    * a system summary (auto-generated by the manager),
    * the most recent :class:`Message` objects (short-term memory),
    * the cumulative token budget.
    """

    model_config = ConfigDict(extra="forbid")

    conversation_id: str
    user_id: Optional[str] = None
    summary: str = Field("", description="Auto-generated rolling summary.")
    recent_messages: List[Message] = Field(default_factory=list)
    token_budget: int = Field(2000, ge=100, le=32_000)
    compressed: bool = Field(False, description="True if older turns were summarised.")
    extra: Dict[str, Any] = Field(default_factory=dict)


# ─── Conversation ─────────────────────────────────────────────────────────


class Conversation(BaseModel):
    """A persistent conversation record.

    A conversation owns a chronological list of messages plus
    lightweight metadata.  Persistent storage is provided by
    :class:`app.services.conversation.ConversationRepository`.
    """

    model_config = ConfigDict(extra="forbid")

    conversation_id: str = Field(
        default_factory=lambda: f"conv-{uuid.uuid4().hex[:12]}"
    )
    user_id: Optional[str] = Field(None, description="Owning user (None = anonymous).")
    title: str = Field("", description="Short human-readable title.")
    status: ConversationStatus = ConversationStatus.ACTIVE
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    expires_at: Optional[datetime] = Field(
        None, description="Optional absolute expiry timestamp."
    )
    ttl_seconds: Optional[int] = Field(
        None, ge=60, description="Optional relative TTL in seconds."
    )
    messages: List[Message] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    tags: List[str] = Field(default_factory=list)
    summary: str = Field("", description="Rolling summary of the conversation.")


# ─── Search & filter ──────────────────────────────────────────────────────


class ConversationFilter(BaseModel):
    """Filter / pagination parameters for listing conversations."""

    model_config = ConfigDict(extra="forbid")

    user_id: Optional[str] = None
    status: Optional[ConversationStatus] = None
    tag: Optional[str] = None
    query: Optional[str] = Field(
        None, description="Free-text query matched against title, summary, messages."
    )
    page: int = Field(1, ge=1)
    page_size: int = Field(20, ge=1, le=200)
    sort_by: str = Field("updated_at", description="Field to sort by.")
    sort_desc: bool = Field(True)


class PaginatedConversations(BaseModel):
    """Paginated conversation list response."""

    model_config = ConfigDict(extra="forbid")

    items: List[Conversation] = Field(default_factory=list)
    total: int = Field(0, ge=0)
    page: int = Field(1, ge=1)
    page_size: int = Field(20, ge=1)
    has_more: bool = False


# ─── Request/Response payloads ───────────────────────────────────────────


class CreateConversationRequest(BaseModel):
    """API request to start a new conversation."""

    model_config = ConfigDict(extra="forbid")

    user_id: Optional[str] = None
    title: str = Field("", description="Optional initial title.")
    metadata: Dict[str, Any] = Field(default_factory=dict)
    tags: List[str] = Field(default_factory=list)
    ttl_seconds: Optional[int] = Field(None, ge=60, le=60 * 60 * 24 * 30)


class AppendMessageRequest(BaseModel):
    """API request to append a message to an existing conversation."""

    model_config = ConfigDict(extra="forbid")

    role: Role
    content: str = Field(..., min_length=1)
    metadata: Dict[str, Any] = Field(default_factory=dict)
    references: Dict[str, str] = Field(default_factory=dict)


__all__ = [
    "AppendMessageRequest",
    "Conversation",
    "ConversationContext",
    "ConversationFilter",
    "ConversationStatus",
    "CreateConversationRequest",
    "Message",
    "PaginatedConversations",
    "Role",
]
