"""create_bm25_metadata_table

Revision ID: 9346ecbe6ad3
Revises: 9e2cc037e137
Create Date: 2026-06-02 08:51:51.325045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9346ecbe6ad3'
down_revision: Union[str, Sequence[str], None] = '9e2cc037e137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bm25_index_metadata',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('index_name', sa.String(length=255), nullable=False),
    sa.Column('corpus_size', sa.Integer(), nullable=False),
    sa.Column('avg_doc_len', sa.Float(), nullable=False),
    sa.Column('vocab_size', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name')
    )
    op.create_index(op.f('ix_bm25_index_metadata_id'), 'bm25_index_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_chunk_id'), 'chunk_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_embedding_model'), 'chunk_embeddings', ['embedding_model'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_id'), 'chunk_embeddings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunk_embeddings_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_embedding_model'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_chunk_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_bm25_index_metadata_id'), table_name='bm25_index_metadata')
    op.drop_table('bm25_index_metadata')
    # ### end Alembic commands ###
